server:
  port: 8989
# datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ly_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ly2lym1314
  # redis
  redis:
    database: 0
    host: 192.168.205.130
    port: 6379
    password:
  #设置上传文件大小，maxFileSize单个文件最大，maxRequestSize单次请求最大
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
    #邮箱
  mail:
    host: smtp.qq.com
    port: 465
    username: y02_coder@qq.com
    password: zplkycqayjtodcij
    default-encoding: UTF-8
    smtp:
      ssl:
        enable: true
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
#    pool:
#      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 10          # 连接池中的最大空闲连接
#      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle: 0           # 连接池中的最小空闲连接
#      timeout: 1000           # 连接超时时间（毫秒）

# My Config
reve:
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  charCaptchaSize: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  captchaEnabled: false
  #邮箱
  subject: 【Rêve个人博客】
  context: 【Reve个人博客】-验证码：
  common: 此验证码用于验证您的身份，有效期5分钟，请勿告知他人。

rocketmq:
  name-server: 192.168.205.130:9876
  producer:
    group: netdisk-group        # 生产者组别
    send-message-timeout: 3000  # 消息发送的超时时间
    retry-times-when-send-async-failed: 2  # 异步消息发送失败重试次数
    max-message-size: 4194304       # 消息的最大长度

logging:
  level:
    RocketmqClient: ERROR
    io:
      netty: ERROR

# minio 文件存储配置信息
minio:
  bucketName: myblog
  endpoint: http://192.168.205.130:21611
  accessKey: admin
  secretKey: admin123

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: hqJXQybMKH4VllaufxdImXozxhWw342A9ilS0Ev-
  secretKey: HgbKmmyXL1VnybPfkXdRbkpP49ui3TgPAt0cv3la
  bucket: ly-blog61
  cdnHttp: http://rvm3i4tms.hn-bkt.clouddn.com/

# jwt配置
jwt:
  secret: Reve2002
  expire: 3
  header: Authorization















